version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: diploma-server-redis
    restart: always
    ports:
      - "6379:6379"
    # volumes:
      # - ./redis/redis_data:/root/redis
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT:-6379}
    command: redis-server --notify-keyspace-events KEA
